modLoader = "javafml"
loaderVersion = "[41,)"
license = "All Rights Reserved"

[[mods]]
    modId = "sprout"
    version = "${version}"
    displayName = "Sprout"
    authors = "Developer - ThatGravyBoat\\nArtist - Frogipher\\nFormer Author - CodexAdrian"
    description = "A vanilla agriculture farming/gardening mod!"

[[dependencies.sprout]]
    modId = "forge"
    mandatory = true
    versionRange = "[41,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.sprout]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.sprout]]
    modId = "geckolib3"
    mandatory = true
    versionRange = "[3.0.12,)"
    ordering = "NONE"
    side = "BOTH"
